package us.mis.acmeexplorer.constant;

public class Descriptions {
    public final static String[] lorem = {
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar cursus velit sit amet ultrices. Sed id iaculis ante. Pellentesque eros lorem, tempus eu efficitur id, sollicitudin at justo. Curabitur laoreet bibendum sodales. Vestibulum eget ligula tempor felis tristique volutpat. Suspendisse tempor erat ex, in commodo orci cursus quis. Nunc a finibus felis, ut blandit arcu. Donec vehicula arcu vel dui fermentum suscipit.\n" +
                    "\n" +
                    "Curabitur dignissim ante non turpis commodo, sit amet condimentum odio dictum. Nullam vitae porta orci. Praesent vitae est placerat, convallis lectus aliquam, aliquam augue.",
            "Curabitur dignissim ante non turpis commodo, sit amet condimentum odio dictum. Nullam vitae porta orci. Praesent vitae est placerat, convallis lectus aliquam, aliquam augue. Sed tellus felis, dictum ac sodales vitae, pulvinar cursus est. Quisque quis nisi cursus quam porta efficitur. Donec vel justo nec elit lacinia eleifend. Vivamus varius condimentum eros nec lobortis. Duis felis libero, viverra ut ligula a, condimentum ullamcorper risus. Duis purus nulla, vestibulum sed ullamcorper id, sagittis eget lectus. Vivamus eros justo, suscipit eget placerat at, pretium ut quam. Etiam sollicitudin viverra justo, et consectetur metus egestas sagittis. Nullam vitae egestas dolor.",
            "Integer non arcu a metus rutrum ultricies. Praesent fermentum, risus a placerat semper, augue nisl vehicula tortor, ut ornare ante lorem nec ante. Etiam malesuada mollis urna, a dignissim metus pulvinar quis.",
            "Phasellus in erat scelerisque, ornare lacus ut, placerat augue. Aenean at ante a dui fringilla bibendum ut vitae urna. Etiam non felis a tellus tincidunt semper vel non est. Sed ultricies libero erat, et sollicitudin arcu volutpat sed. Integer imperdiet velit in est bibendum, a fringilla nunc convallis. Donec quis dignissim diam, vel sagittis arcu. Maecenas vel tincidunt arcu.",
            "Integer non arcu a metus rutrum ultricies. Praesent fermentum, risus a placerat semper, augue nisl vehicula tortor, ut ornare ante lorem nec ante. Etiam malesuada mollis urna, a dignissim metus pulvinar quis. Mauris ultricies eget ipsum venenatis elementum. Morbi ex libero, venenatis eget vehicula nec, posuere non sapien. Vivamus condimentum facilisis diam eget sagittis. Duis non mi sit amet turpis egestas vulputate sed non sem. Donec varius porttitor dui nec consectetur. Sed ut sollicitudin lorem. Ut tortor mauris, fermentum vel lacus quis, pretium faucibus libero. Aliquam vitae auctor eros. Etiam condimentum felis ac felis lobortis posuere. Ut eget lectus tellus. Aenean turpis nisl, posuere at feugiat at, consectetur non est.\n" +
                    "\n" +
                    "Nam efficitur sagittis lobortis. In elementum est libero, vel eleifend tellus vehicula vel. Aliquam luctus lorem lectus, et facilisis lorem eleifend nec. Curabitur ut justo interdum, bibendum augue ut, semper tortor. Aliquam consequat velit non justo facilisis, at volutpat turpis egestas. Curabitur molestie lorem sed magna porttitor, ut euismod leo hendrerit. Suspendisse potenti. Curabitur tempus tortor eu elit ultrices euismod. Donec quis faucibus neque, quis auctor tellus. Aenean maximus vestibulum nunc. Vestibulum consequat gravida viverra. Etiam et quam non augue porttitor congue. Nullam libero libero, ultricies vel diam vitae, sollicitudin posuere eros. Pellentesque enim est, vehicula vitae viverra at, auctor sed lacus. Nulla nec molestie arcu.",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pulvinar cursus velit sit amet ultrices. Sed id iaculis ante. Pellentesque eros lorem, tempus eu efficitur id, sollicitudin at justo. Curabitur laoreet bibendum sodales. Vestibulum eget ligula tempor felis tristique volutpat. Suspendisse tempor erat ex, in commodo orci cursus quis. Nunc a finibus felis, ut blandit arcu. Donec vehicula arcu vel dui fermentum suscipit."
    };
}
